### PR TITLE
For gcc-4.8, std::put_time was failing

### PR DESCRIPTION
**Pull request by gc00**
std::put_time was introduced in commit b2823e39 (July, 2022)

Apparently, gcc-4.8 (and therefore CentOS 7) doesn't support it.  I added a conditional around it: `#if __GCC__ > 4`

### CODE REVIEW

File: jalib/jassert.cpp [hunk 1]
```diff
@@ -87,7 +87,14 @@ jassert_internal::JAssert::JAssert(const char* type, bool exitWhenDone)
...
   }
 
-  ss << "[" << std::put_time(&localTime, "%F, %T.") << ms << ", "
+  ss << "[" 
+#if __GCC__ > 4
+    // put_time introduced in commit b2823e39 (July, 2022)
+    // In CentOS 7 using gcc/g++ 4.8.5, this fails with:
+    //      error: ‘put_time’ is not a member of ‘std’ 
+     << std::put_time(&localTime, "%F, %T.")
+#endif
```
Comment (JainTwinkle) [inline jalib/jassert.cpp:96]: Why are we not adding an else condition with a C version of std::put_time?

**Comment by karya0** [comment]
We can replace it with a C-style implementation. I’ll generate a separate
PR.

**Review by JainTwinkle — APPROVED** [review]
@karya0 promises to generate a separate PR for the c-style implementation. This PR is ready to get merged.

**Review by karya0 — APPROVED** [review]
